#import.sql file

insert into residencia (id, ciudad, pais, provincia) values ('1', 'Santa Rosa', 'Argentina', 1);
insert into residencia (id, ciudad, pais, provincia) values ('2', 'San Luis', 'Argentina', 2);
insert into residencia (id, ciudad, pais, provincia) values ('3', 'Carlos Paz', 'Argentina', 3);
insert into residencia (id, ciudad, pais, provincia) values ('4', 'Cura Brochero', 'Argentina', 3);
insert into bodega (id, anio, descripcion, link, nombre, cod_residencia) values ('1', '1900', 'La Bodega pampeana por excelencia',"link","Senheteizer", 1);
insert into bodega (id, anio, descripcion, link, nombre, cod_residencia) values ('2', '1950', 'La Bodega pampeana por excelencia',"link","Rutini", 2);
insert into bodega (id, anio, descripcion, link, nombre, cod_residencia) values ('3', '1978', 'La Bodega pampeana por excelencia',"link","La Gata Flora", 3);
insert into bodega (id, anio, descripcion, link, nombre, cod_residencia) values ('4', '1920', 'La Bodega pampeana por excelencia',"link","Chandon", 2);

insert into tipo_vino (id, nombre, descripcion) values ('1', 'blanco', 'Es el obtenido a partir de uvas blancas. Aunque es poco frecuente, también puede ser obtenido a partir de uvas tintas de pulpa no coloreada a las que se les separa el hollejo (piel de la uva, parte externa, cubierta). Los vinos hechos de uvas blancas no son tan bien valorados por el público general como son los provenientes de uvas rojas; valoración subjetiva que solo priva de grandes vinos a quienes la ejercen. Las personas piensan en los vinos blancos como caldos ácidos y poco interesantes, pero estas mismas características las podemos encontrar en los vinos tintos de baja calidad.');
insert into tipo_vino (id, nombre, descripcion) values ('2', 'rosado', 'Es el obtenido a partir de uvas tintas a las que no se les ha separado los hollejos.');
insert into tipo_vino (id, nombre, descripcion) values ('3', 'tinto', 'Es el obtenido a partir de uvas tintas a las que se les ha separado parcialmente los hollejos. También puede provenir de mezcla de uvas blancas y tintas. Los vinos tintos gozan de una aceptación casi unánime entre los aficionados del vino, y la prueba está en la cantidad de variedad que ofrece el mercado en relación a los vinos blancos o rosados que podemos comprar en cualquier tienda.');
insert into tipo_vino (id, nombre, descripcion) values ('4', 'clarete', 'El nombre proviene de la perversión e imitación de "Claret", el vino pálido tinto de origen Bordeaux. Comúnmente son elaborados con uvas tintas y blancas, realizando la fermentación con los hollejos. Su elaboración está justificada cuando se quiere producir vino con suficiente color rosado pero no se dispone de la cantidad necesaria de uvas tintas.');

insert into edad (id, nombre, descripcion) values ('1', 'Joven', 'Son los que no han tenido ningún tipo de crianza en madera o esta crianza ha sido mínima. Son vinos que conservan mucho las características varietales de las uvas de las que proceden y de consumo ideal en los 12-24 meses después de la vendimia.');
insert into edad (id, nombre, descripcion) values ('2', 'Crianza', 'Mínimo de seis meses en madera y hasta dos años en botella. Crianza será tanto el vino que tiene un año en madera y otro en botella como el que tiene 18 meses en madera y 6 en botella.');
insert into edad (id, nombre, descripcion) values ('3', 'Reserva', 'Son vinos con tres años de envejecimiento (2 años los blancos y rosados), de los cuales al menos uno en barrica (6 meses los blancos y rosados).');
insert into edad (id, nombre, descripcion) values ('4', 'Gran Reserva', 'Son vinos con cinco años de envejecimiento (4 años los blancos y rosados), de los cuales al menos 18 meses en barrica (6 meses los blancos y rosados).');

insert into uva (id, nombre, descripcion) values ('1', 'Chenin', 'Originaria del valle del río Loire, en Francia, de gran calidad, con ella se obtienen atractivos vinos blancos frutados, ligeros y frescos. Hay cantidad en Argentina, donde es mayormente utilizada para corte con otros vinos. Es así mismo una variedad muy interesante para elaborar vinos dulces. Se la conoce también como pineau o pinot de la Loire.');
insert into uva (id, nombre, descripcion) values ('2', 'Chardonay', 'Considerada la reina de las uvas blancas, produce en la Borgoña Francesa algunos de los más renombrados y caros vinos blancos del mundo. Su cultivo se extendió exitosamente a muchos países, obteniéndose con ella vinos de aroma voluptuoso, aptos para la fermentación y el estacionamiento en barriles de roble nuevo. También muy usado para vinos de base de espumosos tipo Champagne.');
insert into uva (id, nombre, descripcion) values ('3', 'Riesling', 'Cepaje emblemático de la vitivinicultura alemana, el Riesling se utiliza en ese país para vinos secos y dulces, donde aporta su particular y especiado perfume. Hay poco Riesling verdadero en Argentina.');
insert into uva (id, nombre, descripcion) values ('4', 'Semillón', 'Variedad de uva de la región de Bordeaux, en Francia, donde produce blancos secos y dulces, algunos muy famosos, como el licoroso Sauternes. En Argentina se desarrolla bastante bien en zonas frías, especialmente Tupungato, en Mendoza, y el Valle de Río Negro.');
insert into uva (id, nombre, descripcion) values ('5', 'Torrontés', 'La uva Torrontés da origen al vino blanco más típico de la Argentina, ya que sus características se consideran únicas en el mundo. De origen incierto, su parentesco más probable está asociado con los moscateles, con los que guarda un cierto parecido aromático. Se lo cultiva en todas las regiones vinícolas Argentinas, aunque sus zonas preferenciales están en Cafayate (Salta) y el Valle de Chilecito (La Rioja).');
insert into uva (id, nombre, descripcion) values ('6', 'Sauvignon Blanc', 'Otro cepaje del sudoeste de Francia, donde produce importantes vinos. Su difusión es muy ampliada en el mundo, destacándose especialmente en Nueva Zelanda y Chile. En Argentina se está empezando a desarrollar muy bien, con vinos de aroma intenso y con matices herbáseos.');

insert into uva (id, nombre, descripcion) values ('7', 'Cabernet Sauvignon', 'La Cabernet Sauvignon es la uva roja más famosa del mundo, muy utilizada por su color intenso y su estabilidad. Los aromas más típicos nos recuerdan a violetas, bayas, frambuesa, moras y café sin tostar. Es común encontrar notas a pimiento verde que muchos enólogos (los más) lo atribuyen a una mala maduración del caldo y no a una característica deseable. Su color es rojo intenso y es ideal para acompañar platos de carne y salsas espesas. Es consumida y cultivada en prácticamente todos los países donde se produce vino.');
insert into uva (id, nombre, descripcion) values ('8', 'Malbec', 'Otro cepaje originario del sudoeste de Francia, donde paulatinamente ha sido dejado de lado ya que allí no produce gran calidad. En Argentina encontró la tierra y el clima ideales para su desarrollo, dando excelentes vinos de buen color y cuerpo, de notable intensidad y concentración. Por ello se lo considera el tinto argentino más típico. La Malbec se cultiva en todas las regiones vitivinícolas Argentinas, destacándose la zona de Luján de Cuyo (Mendoza).');
insert into uva (id, nombre, descripcion) values ('9', 'Merlot', 'También de Bordeaux, donde integra los cortes con el Cabernet Sauvignon. Los aromas y sabores de uno y otro son similares, pero en la boca el Merlot es más débil que la del Cabernet, el Merlot es muy utilizado para cortes con otros vinos más robustos. Pero sus varietales alcanzan gran calidad.');
insert into uva (id, nombre, descripcion) values ('10', 'Syrah', 'Uva de origen supuestamente persa, desde donde habría llegado al valle de río Rodamo (Francia) por obra de los cruzados. Hoy está en expansión en todo el mundo ya que produce vinos de buena calidad, color rojo intenso, aroma profundo y sabor recio. Madura muy bien en botella, donde adquiere matices especiados.');
insert into uva (id, nombre, descripcion) values ('11', 'Pinot Noir', 'cepaje que da origen a los famosos Borgoñas Tintos franceses. A diferencia de otras variedades, no suele reproducir sus mejores virtudes fuera del terruño original. Por esa razónse lo cultiva es escasas regiones. Vinifcado en blanco, integra muchos de los vinos base para espumosos.');
insert into uva (id, nombre, descripcion) values ('12', 'Sangiovese', 'Variedad Italiana de la Toscana, es la base del afamado Chianti. En Argentina se la cultiva de hace largo tiempo, a veces bajo el erróneo nombre de Lambrusco. En los últimos tiempos se lo elabora como varietal para la exportación, o como componente de cortes diversos, donde aporta su agradable sabor frutado y floral, con ciertos matices violetas.');
insert into uva (id, nombre, descripcion) values ('13', 'Bonarda', 'Otra variedad Italiana, es este caso del Piemonte, que siempre contó en Argentina con una superficie de cultivo. Sin embargo, sólo en los últimos años se la reconoce como apta para elaborar vinos de calidad. Tiene la especial cualidad de mejorar y equilibrar vinos de corte.');
insert into uva (id, nombre, descripcion) values ('14', 'Tempranillo', 'Es la uva más famosa y la más usada de España. Su origen la sitúa como una descendiente de la uva Pinot Noir francesa. Debido a su baja acidez y poca presencia de azúcar es muy común mezclarla con un pequeño porcentaje de otras cepas para lograr mejores caldos. Su color es rojo rubí y sus aromas más representativos son los de frutos del bosque, bayas, ciruela y tabaco. Tiene una alta capacidad de envejecimiento, lo que la hace ideal para su maduración en barricas. También es usada en Portugal y algunos países del Nuevo mundo.');



